version: '3.2'
services:
  nginx:
    image: prooph/nginx:www
    ports:
        - "${NGINX_PORT}:80"
        - "443:443"
    links:
      - php:php
    volumes:
      - .:/var/www

  php:
    image: prooph/php:7.1-fpm
    links:
      - mariadb:mariadb
    volumes:
      - .:/var/www

  mariadb:
    image: mariadb
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=cargo_sample

#  adminer:
#    image: adminer:4.3
#    ports:
#      - ${ADMINER_PORT}:8080
